
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  security:
    mock:
      users:
        admin:
          password: admin
          roles:
          - admin
        user:
          password: user
        content-manager:
          policies:
            - cap.ContentManager
          attributes:
            ias_apis:
              - ManageBookshopContent
        stock-manager:
          policies:
            - cap.StockManager
        stock-manager-fiction:
          policies:
            - local.StockManagerFiction
  data-source:
    auto-config:
      enabled: false

management:
  endpoint:
    health:
      show-components: always # shows individual indicators
      show-details: always
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health # only expose /health as web endpoint
          - beans
  health:
    defaults.enabled: false # turn off all indicators by default
    ping.enabled: true
    db.enabled: true
    ams.enabled: true

logging:
  level:
    com:
      sap:
        cds:
          security:
            authorization: TRACE
    com.sap.cloud.security.ams: DEBUG
    com.sap.cloud.security.ams.samples: DEBUG
    com.sap.cloud.security.ams.cap: DEBUG
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
